
import './globals.css'
import Header from '@/components/Header'
import Navbar from '@/components/Navbar'
import Providers from './providers'

export const metadata = {
  title: 'IMDB CLONE',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
      <Header />
      <Navbar/>
     <main> {children} </main>
     </Providers>
      </body>
    </html>
  )
}
